title: AbitareSmart
lang: it
locale: it_IT
description: > # this means to ignore newlines until "show_excerpts:"
  Domotica semplice, sicura e su misura. Progettiamo case intelligenti che lasciano spazio alla vita.
logo: /assets/img/brand/abitaresmart-logo-icon.png
baseurl: ""
url: https://abitaresmart.com

permalink: "/blog/:title/"

plugins:
  - jekyll-feed
  - jekyll-soopr-seo-tag
  - jekyll-sitemap
  - jekyll-minifier

css_dir: "assets/css" # defaults to "css"

highlighter: rouge

collections:
  posts:
    output: true
    permalink: "/blog/:title/"
  pages:
    output: true
    permalink: "/:title"

# soopr:
#  publish_token: "" # sign up at https://www.soopr.co to get your publish token and personalize share and reaction options


twitter:
  card: summary_large_image

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - package.json
  - package-lock.json
  - README.md
  - postcss.config.js
  - purgecss.config.js
  - tailwind.config.js
  - assets/fonts
  - assets/img/cards
  - assets/img/bg.png
  - assets/img/shape.svg
  - assets/img/logo.png
  - assets/img/AbitareSmart-Logo.png
  - assets/img/blog/thumb
  - .gitignore
  - vendor
